#######################
# Spring boot Setting #
#######################
server:
  port: 81

spring:
  application:
    name: springboot-CV_Site

  # 자동 리로드
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  #################
  # Mysql Setting #
  #################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cv_site?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: inha1468%

  ############
  # JPA 설정  #
  ############
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: update      # create, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # 카멜표기를 스네이크 표기로 변환
    show-sql: true          # SQL 구문 보이기
    properties:
      hibernate:
        format_sql: true    # 포멧 처리해서 보이기
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8 버전 사용

############
# Log 설정  #
############
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

  ####################
  # Security Setting #
  ####################

  security:
    user:
      name: test@test.com
      password: 1111

  ################
  # File Setting #
  ################

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

cvImgLocation: D:/cv_site/cv
uploadPath: file:///D:/cv_site/